# fly.toml app configuration file generated for server-driven-htmx-workbook on 2025-03-13T20:24:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-driven-htmx-workbook'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# WebSockets service configurations
[[services]]
  internal_port = 3002
  protocol = "tcp"
  
  [[services.ports]]
    port = 3002
    handlers = ["http"]
    force_https = true

[[services]]
  internal_port = 3003
  protocol = "tcp"
  
  [[services.ports]]
    port = 3003
    handlers = ["http"]
    force_https = true

[[services]]
  internal_port = 3004
  protocol = "tcp"
  
  [[services.ports]]
    port = 3004
    handlers = ["http"]
    force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
